# Change colour of prompt text
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
# make a pretty print method for ls
alias ls='ls -GFh'

# alias for hub.github
alias git=hub
# alias to open rstudio easy
alias rstudio='open -a RStudio'
